[book]
authors = ["Dangerise"]
language = "zh_cn"
multilingual = false
src = "src"
title = "Dangerise's Blog"


[output.html]
edit-url-template = "https://github.com/Dangerised/blog/blob/master/{path}"
git-repository-url = "ttps://github.com/Dangerised/blog"
