[book]
authors = ["Dangerise"]
language = "zh_cn"
multilingual = false
src = "src"
title = "Dangerise's Blog"

[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
edit-url-template = "https://github.com/Dangerised/blog/blob/master/{path}"
git-repository-url = "https://github.com/Dangerised/blog"
additional-js = [
    "assets/mermaid.min.js",
    "assets/mermaid-init.js",
    "assets/elasticlunr.js",
    "assets/fzf.umd.js",
]
